# Generated by Django 2.1.5 on 2019-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employe_sallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='sallary',
            field=models.IntegerField(default=0),
        ),
    ]
