# Generated by Django 2.1.5 on 2019-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190122_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='false', max_length=20)),
                ('name', models.CharField(blank='false', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNo', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
