# Generated by Django 2.1.5 on 2019-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190128_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='false', max_length=100)),
                ('branch', models.CharField(blank='false', max_length=50)),
                ('year', models.IntegerField()),
                ('rollNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileNo', models.IntegerField()),
                ('image', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
